let modeloJson = [
  {
    id: 1,
    name: 'Camiseta Rosa',
    img: 'img/camisetaR.jpg',
    price: 20.19,
    sizes: ['malha', 'algodão', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 2,
    name: 'Camiseta Amarela',
    img: 'img/camisetaAM.jpg',
    price: 18.00,
    sizes: ['algodão', 'malha', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 3,
    name: 'Camiseta Preta',
    img: 'img/camisetaP.jpg',
    price: 20.45,
    sizes: ['dry', 'malha', 'algodão'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 4,
    name: 'Camiseta Pink',
    img: 'img/camisetaPK.jpg',
    price: 19.77,
    sizes: ['algodão', 'malha', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 5,
    name: 'Camiseta Azul',
    img: 'img/camisetaA.jpg',
    price: 20.43,
    sizes: ['malha', 'algodão', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 6,
    name: 'Camiseta Vermelha',
    img: 'img/camisetaV.jpg',
    price: 18.55,
    sizes: ['malha', 'dry', 'algodão'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 7,
    name: 'Camiseta Marrom',
    img: 'img/camisetaM.jpg',
    price: 21.36,
    sizes: ['malha', 'dry', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
   {
    id: 7,
    name: 'Camiseta Verde',
    img: 'img/camisetaVD.jpg',
    price: 19.99,
    sizes: ['malha', 'dry', 'algodão'],
    description: 'Blusa Básica Manga Curta',
  },
   {
    id: 8,
    name: 'Camiseta Lilás',
    img: 'img/camisetaL.jpg',
    price: 18.60,
    sizes: ['malha', 'dry', 'algodão'],
    description: 'Blusa Básica Manga Curta',
  }, 
];